// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoCAT7V9IW0fQ2nkazn3xd095bKWPDhrU',
    appId: '1:961641564690:web:768d0a273f1447232166cb',
    messagingSenderId: '961641564690',
    projectId: 'notes-9e76d',
    authDomain: 'notes-9e76d.firebaseapp.com',
    storageBucket: 'notes-9e76d.appspot.com',
    measurementId: 'G-VELN47G91S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQm56PF8GgpcIKr4Gna2f1F8S73btWhcw',
    appId: '1:961641564690:android:d37cecd5f096b7832166cb',
    messagingSenderId: '961641564690',
    projectId: 'notes-9e76d',
    storageBucket: 'notes-9e76d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQZzcfaUWUL70sASyDFLCnvo4bruT2DM',
    appId: '1:961641564690:ios:ceca6a23e3eaf6912166cb',
    messagingSenderId: '961641564690',
    projectId: 'notes-9e76d',
    storageBucket: 'notes-9e76d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQZzcfaUWUL70sASyDFLCnvo4bruT2DM',
    appId: '1:961641564690:ios:53641189bf3d8f652166cb',
    messagingSenderId: '961641564690',
    projectId: 'notes-9e76d',
    storageBucket: 'notes-9e76d.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
